### ISSUE TITLE
uncaught exception

### ISSUE THREAD

**Issue by achezzoh** [malkusch/php-autoloader#7]
my autoloder works(meaning it actually loads the classes) but i get some very long error message at the bottom of the page. the error has something to do with an uncaught exception, failure to move some file in appdata/local/tmp(i use windows), and its thrown in the file .... index/autoloaderindex_file.php line 304. this is just a quick summary of the error message, but i hope you understand where its coming from, otherwise i can post all of it later, its just that i dont have my computer with me right now. please help and forgive my sketchiness...

**Comment by malkusch** [comment]
The complete stack trace would help more.

**Comment by achezzoh** [comment]
Here is the complete stack trace:
```
Fatal error: Uncaught exception 'malkusch\autoloader\AutoloaderException_Index_IO' with message 'Could not move new index C:\Users\stv\AppData\Local\Temp\Aut8D7F.tmp to C:\Users\stv\AppData\Local\Temp\malkusch\autoloader\AutoloaderIndex_SerializedHashtable_GZ29df4f0933bac2917615ec0d73aad8ea: rename(C:\Users\stv\AppData\Local\Temp\Aut8D7F.tmp,C:\Users\stv\AppData\Local\Temp\malkusch\autoloader\AutoloaderIndex_SerializedHashtable_GZ29df4f0933bac2917615ec0d73aad8ea): The system cannot find the path specified. (code: 3)' in C:\xampp\htdocs\FYP\autoloader\Autoloader\index\AutoloaderIndex_File.php:304 Stack trace: #0 C:\xampp\htdocs\FYP\autoloader\Autoloader\index\AutoloaderIndex.php(275): malkusch\autoloader\AutoloaderIndex_File->saveRaw() #1 C:\xampp\htdocs\FYP\autoloader\Autoloader\index\AutoloaderIndex.php(316): malkusch\autoloader\AutoloaderIndex->save() #2 [internal function]: malkusch\autoloader\AutoloaderIndex->__destruct() #3 {main} thrown in C:\xampp\htdocs\FYP\autoloader\Autoloader\index\AutoloaderIndex_File.php on line 304
```

**Comment by malkusch** [comment]
Sorry, I have no idea what's going wrong.

**Comment by malkusch** [comment]
Thank you. This is fixed now in 1.14.6.

**Comment by achezzoh** [comment]
Thank you very much.

**Comment by achezzoh** [comment]
Hi, I am back with one more question.
I have the following folder structure in my project:
```
htdocs/proj/index.php
htdocs/proj/admin/index.php
htdocs/proj/classes/*.php
htdocs/proj/autoloader/
```
```htdocs``` is the server root, ```proj``` is my project root folder, ```classes``` is where i have the class files and the ```index.php``` files are the pages a user navigates to and they in turn include and use the class files. My problem is that the root index works fine, but ```admin/index.php``` gives the 'class not found' error. This is the code i use to include autoloader in ```admin/index.php```
```
require "../autoloader/autoloader.php";
Autoloader::getRegisteredAutoloader()->remove();
$autoloader = new Autoloader("../classes");
$autoloader->register();
```
What am i not doing wrong, or am i supposed to have a separate copy of the autoloader since the two index.php  files are at different folder levels?
